language: python
python:
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_c5fd3201494e_key -iv $encrypted_c5fd3201494e_iv
  -in config.json.enc -out config.json -d
install:
- pip install pipenv
- pipenv install
script: python3 bot.py
